version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-1
      - backend-2

  backend-1:
    image: your-backend-image-1
    # other configuration for your backend

  backend-2:
    image: your-backend-image-2
    # other configuration for your backend
